### ISSUE TITLE
Using other datasets

### ISSUE THREAD

**Issue by j-faria** [shib0li/Scalable-GPRN#2]
Hello, 
I would like to try this model on a dataset with a different shape than Jura, but I can't figure out the correct inputs.

My dataset has one input (so `X_all` has shape (N,1)) and D outputs (so `Y_all` has shape (N,D)). 
D is usually small (1-5). 

In `DataProcess.py`, what should `Dlist` be set to?
I found the variables `SGPRN.D1`, `SGPRN.D1`, and `SGPRN.D3`. Does the code always assume 3 outputs?

**Comment by shib0li** [comment]
> Hello,
> I would like to try this model on a dataset with a different shape than Jura, but I can't figure out the correct inputs.
> 
> My dataset has one input (so `X_all` has shape (N,1)) and D outputs (so `Y_all` has shape (N,D)).
> D is usually small (1-5).
> 
> In `DataProcess.py`, what should `Dlist` be set to?
> I found the variables `SGPRN.D1`, `SGPRN.D1`, and `SGPRN.D3`. Does the code always assume 3 outputs?

**Comment by shib0li** [comment]
Hi, it is not the dimension of the ouptut. It is a choice of output dimension factorization. I replied to your email, and you can check the details.

**Comment by Harshp1802** [comment]
Hi @shib0li, 
It would be great if you could explain the Dlist parameter here.
My dataset has (X_all.shape = (N,8) and Y_all.shape = (N,1)). Just trying on a single output dataset.
Thanks!

**Comment by shib0li** [comment]
Hi @Harshp1802, 

Apologize for the late response, Dlist is the output factorization list, in our paper, we assume the output space is huge, say there are 1m outputs, the Dlist can be defined as [100, 100, 100]. In other words, Dlist is a hyperparameter that defines the internal structure of our algorithm. In your case, your input space is small and output space is small, I think a single exact GP can do the work. Our model is for multi-outputs/tasks GPs. If you still have questions, you can send me an email, I don't check my repo very often. 

-Shibo
